version: '3.1'  # 3.1 for secrets

networks:
  backend:
  frontend:

services:
  nginx:
    image: nginx:1.13
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend
    links:
      - product:app  # "app" is the hostname used in proxy_pass directive

  product:
    #build: . # current dir Dockerfile
    image: jugaljoshi/nginx-node-mysql-host  # work in two ways for build and official image
    # (docker-compose down --rmi local) local => for which build is defined and image is not
    container_name: product
    restart: always
    environment:
      - NODE_ENV=development
      - DB_HOST=db:3306
      - DB_USER=root
      - DB_PASSWORD=toor
    volumes:
      - /home/jugal/microservice:/productservice
    depends_on:
      - db
    networks:
      - backend
      - frontend
    command: nodemon ./bin/www


  db:
    image: mysql
    container_name: mysql
    restart: always
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=bigbasket
      - MYSQL_USER=root
      - MYSQL_PASSWORD=toor
    networks:
      backend:
        aliases:
          - dbserver

