apiVersion: v1
kind: Service
metadata:
  name: internal-service
  labels:
    app: mysql-service
spec:
  selector:
    pod: mysql-pod
  ports:
    - name: mysql
      port: 3306
      targetPort: mysql-port
      protocol: TCP


---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-database-env
  namespace: default
data:
  MYSQL_ROOT_PASSWORD: "toor"
  MYSQL_DATABASE: "bigbasket"
  MYSQL_USER: "root"


---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        pod: mysql-pod
    spec:
      containers:
        - name: mysql-container
          image: mysql:5.6
          ports:
            - name: mysql-port
              protocol: TCP
              containerPort: 3306
          envFrom:
            - configMapRef:
                name: mysql-database-env

          volumeMounts:
            - name: mysql-vol
              mountPath: "/var/lib/mysql"

      volumes:
        - name: mysql-vol
          emptyDir: {}


# https://stackoverflow.com/questions/39910225/how-to-connect-mysql-running-on-kubernetes
# https://portworx.com/mysql-kubernetes/