module.exports = {
    PRODUCT_LIST: "product_list",
    CATEGORY: "pc",
    BRAND: "pb",
    SEARCH: "ps",
    SHOP: "sis",
    SHOP_OR_EXPRESS: "sis",
    BRAND_CATEGORY: "pbpc",
    BUNDLE_PACK: "bundle-pack",
    NOW_AT_BB: "nowatbb",
    NEW_AT_BB: "new_launches",
    NEW_AND_NOW_AT_BB: "nl",
    ALL_OFFERS: "all-offers",
    SPECIALITY_STORE: "sps",
    SPECIALITY_CATEGORY: "spc",
    TAG_SEARCH: "ts",
    MANUAL_TAG: "manual_tag",
    AUTO_TAG: "auto_tag",
    SMART_BASKET: "mem.sb",
    DYF_TYPE: "dyf",
    SYSTEM_SHOPPING_LIST: "ssl",
    RECOMMENDATIONS: 'reco',
    ALL_OFFERS_DISCOUNT: 'd',
    COSMETIC_CHILDREN_DISPLAY_COUNT: 5,
    COSMETIC_STORE_TAG_GROUP: 'parent_child_variant_type',
    COSMETIC_STORE_TAG_VALUE: 'colour',
    SPECIALITY_STORE_SCOPE: "speciality_store",
    OFFERS_PAGE: "offers",
    CUSTOMPAGE_FEATURED_PRODUCT: 'cpfp',
    PS_CAT_BRANDS_SELECTED: 'brand_selected',
    COMBO: 'combo_list',
    PROMO_OFFER_BY_CATEGORY: "promo-offers-cat",
    PROMO_OFFERS_BY_TYPE: "promo-offers-type",
    PROMO_OFFERS_FOR_YOU: "promo-offers-foryou",

    FI_TYPE_NORMAL: "normal",
    FI_TYPE_EXPRESS: "darkstore-express",

    NO_SHIPMENT_INFO    : "NO_SHIPMENT_INFO",
    WILL_GO_TOGETHER    : "WILL_GO_TOGETHER",
    MAY_GO_SEPARATELY   : "MAY_GO_SEPARATELY",
    WILL_GO_SEPARATELY  : "WILL_GO_SEPARATELY",
    ANNOTATION_TYPES : {
        NO_SHIPMENT_INFO      : '',
        WILL_GO_TOGETHER      : 'All items will go together in a single shipment',
        MAY_GO_SEPARATELY     : 'Some products may get delivered in multiple shipments',
        WILL_GO_SEPARATELY    : 'Some products will get delivered in multiple shipments'
    }
};